#!/bin/bash

# MSMC - Merge phased genotypes with unphased VCFs
#
# This script overlays the phased genotypes generated by WhatsHap
# onto the corresponding unphased VCF files for each sample and
# scaffold. The resulting VCFs are used for downstream MSMC analysis.

set -euo pipefail
shopt -s nullglob

############################
# PATHS
############################

BAMS=(
	 /mnt/SERB_NAS_Biogeography/raw-genomics/NCGM-5022/alignment_files/*rmdup.bam
        /mnt/SERB_NAS_Biogeography/raw-genomics/NCGM-5023/alignment_files/*rmdup.bam
)

WHATSHAP_DIR="/media/birdlab/HDD_16/raw_seq_data/MSMC/TT/whatshap"
MERGED_ROOT="/media/birdlab/HDD_16/raw_seq_data/MSMC/TT/whatshap_merged"

BCFTOOLS="/home/birdlab/softs/bcftools-1.10.2/bcftools"

THREADS=20   # adjust to cluster size

mkdir -p "$MERGED_ROOT"

echo "Starting PARALLEL phased → unphased overlay..."

############################
# LOOP OVER BAMs (same parsing logic)
############################

for BAM in "${BAMS[@]}"; do

    BASE=$(basename "$BAM")

if [[ "$BASE" == *_rmdup.bam ]]; then
    SAMPLE="${BASE%_rmdup.bam}"
else
    echo "Cannot parse sample name from $BASE"
    exit 1
fi

    echo "================================="
    echo "Processing sample: $SAMPLE"
    echo "================================="

    UNPHASED_DIR="${WHATSHAP_DIR}/${SAMPLE}/unphased"
    PHASED_DIR="${WHATSHAP_DIR}/${SAMPLE}/phased"
    MERGED_DIR="${MERGED_ROOT}/${SAMPLE}"

    mkdir -p "$MERGED_DIR"

    export SAMPLE UNPHASED_DIR PHASED_DIR MERGED_DIR BCFTOOLS

    ############################################
    # PARALLEL MERGE PER SCAFFOLD
    ############################################

    parallel -j "$THREADS" --halt soon,fail=1 '
        PHASED_VCF={}
        BASE=$(basename "$PHASED_VCF" _biallelic_phased.vcf.gz)

        UNPHASED_VCF="'"$UNPHASED_DIR"'/${BASE}_biallelic_unphased.vcf.gz"
        OUT="'"$MERGED_DIR"'/${BASE}_merged_final.vcf.gz"

        if [[ ! -f "$UNPHASED_VCF" ]]; then
            echo "Missing UNPHASED for $BASE"
            exit 1
        fi

        echo "Overlaying phased onto unphased: $BASE"

        "'"$BCFTOOLS"'" annotate \
            --threads 3 \
            -a "$PHASED_VCF" \
            -c FORMAT/GT \
            -O z \
            -o "$OUT" \
            "$UNPHASED_VCF"

        "'"$BCFTOOLS"'" index -c "$OUT"

    ' ::: "${PHASED_DIR}"/*_biallelic_phased.vcf.gz

done

echo "Merge completed successfully."
